#!/bin/bash

# get openai key from secret file
source $OPENAI_CONFIG_PATH 

# read the prompt from argument
prompt="$1"
# send request to openai api
response=$(curl -s $ENDPOINT_URL -H "Authorization: Bearer $OPENAI_KEY" \
	-H "Content-Type: application/json" \
	-d '{
	"model": "gpt-3.5-turbo",
	"messages": [{"role": "user", "content": "'"$prompt"'"}]
	}'
)

# get status code
status_code=$?

# parse with jq
if [ $status_code -eq 0 ]; then
  text=$(echo $response | jq -r '.choices[0].message.content')
  echo $text
else
  error=$(echo $response | jq -r '.choices[0].text')
  echo $response
  echo "Error: $error"
fi
