#!/bin/bash

# read environment variables
source $OBSI_CONFIG_PATH 

cd ${REPO_DIR}
${GIT} pull --rebase
${GIT} add .
${GIT} commit -m "${HOSTNAME} `date +%Y%m%d%H%M%S`"
${GIT} push ${REPO_LINK}
${GIT} pull --rebase
${GIT} push
